apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: taskdispacher
  namespace: default
subjects:
- kind: ServiceAccount
  name: task-dispacher
roleRef:
  kind: Role 
  name: task-dispacher
  apiGroup: rbac.authorization.k8s.io